[build]
  command = "npm run build"
  functions = "functions"  # Netlify Functions directory
  publish = "dist"        # Your output directory

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200